"""Validate recipe Front Matter and generate the root README recipe index."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "PyYAMLが必要です。python -m pip install -r requirements.txt を実行してください。"
    ) from exc


ROOT = Path(__file__).resolve().parents[1]
SKILL_RELATIVE_PATH = Path(".skills/recipe-frontmatter/SKILL.md")
README_RELATIVE_PATH = Path("README.md")
EXCLUDED_NAMES = {"README.md", "agents.md"}
GENERATED_NOTICE = "<!-- Generated by scripts/recipe_index.py. Do not edit manually. -->"
RECIPE_INDEX_START = "<!-- recipe-index:start -->"
RECIPE_INDEX_END = "<!-- recipe-index:end -->"
TYPE_ORDER = {"standard": 0, "history": 1, "reference": 2}
BACKTICK = chr(96)
HISTORY_TITLE_DATE_PREFIX = re.compile(r"^\d{4}-\d{2}-\d{2}(?:\s|$)")


class RecipeIndexError(ValueError):
    """Raised for invalid repository metadata or index generation input."""


@dataclass(frozen=True)
class SkillSchema:
    required_fields: tuple[str, ...]
    optional_fields: tuple[str, ...]
    document_types: frozenset[str]
    categories: frozenset[str]
    statuses: frozenset[str]
    source_types: frozenset[str]
    array_fields: frozenset[str]
    date_fields: frozenset[str]

    @property
    def allowed_fields(self) -> frozenset[str]:
        return frozenset((*self.required_fields, *self.optional_fields))


@dataclass(frozen=True)
class RecipeDocument:
    path: Path
    metadata: dict[str, Any]
    body: str | None = None


def _section(text: str, heading: str, level: int) -> str:
    marker = re.compile(rf"^{re.escape('#' * level)}\s+{re.escape(heading)}\s*$", re.MULTILINE)
    match = marker.search(text)
    if match is None:
        raise RecipeIndexError(f"Skillに見出しがありません: {heading}")
    next_heading = re.compile(rf"^{re.escape('#' * level)}\s+.+$", re.MULTILINE)
    next_match = next_heading.search(text, match.end())
    return text[match.end() : next_match.start() if next_match else len(text)]


def _field_section(text: str, field: str) -> str:
    marker = re.compile(
        rf"^##\s+{BACKTICK}?{re.escape(field)}{BACKTICK}?\s*$", re.MULTILINE
    )
    match = marker.search(text)
    if match is None:
        return ""
    next_match = re.search(r"^##\s+.+$", text[match.end() :], re.MULTILINE)
    end = match.end() + next_match.start() if next_match else len(text)
    return text[match.end() : end]


def _first_yaml_block(text: str) -> dict[str, Any]:
    fence = BACKTICK * 3
    match = re.search(rf"{fence}yaml\s*\n(.*?)\n{fence}", text, re.DOTALL)
    if match is None:
        raise RecipeIndexError("SkillにYAML例がありません")
    example_lines = match.group(1).splitlines()
    if example_lines and example_lines[0].strip() == "---":
        example_lines = example_lines[1:]
    if example_lines and example_lines[-1].strip() == "---":
        example_lines = example_lines[:-1]
    value = yaml.safe_load("\n".join(example_lines))
    if not isinstance(value, dict):
        raise RecipeIndexError("SkillのYAML例がマッピングではありません")
    return value


def _parse_skill_schema(skill_path: Path) -> SkillSchema:
    text = skill_path.read_text(encoding="utf-8-sig")
    required_example = _first_yaml_block(_section(text, "必須フィールド", 1))
    optional_example = _first_yaml_block(_section(text, "任意フィールド", 1))
    required = tuple(required_example)
    optional = tuple(optional_example)

    document_type_section = _field_section(text, "document_type")
    document_type_match = re.search(
        rf"{BACKTICK}(standard){BACKTICK}.*?{BACKTICK}(history){BACKTICK}.*?{BACKTICK}(reference){BACKTICK}",
        document_type_section,
        re.DOTALL,
    )
    if document_type_match is None:
        raise RecipeIndexError("Skillからdocument_typeの許可値を読み取れません")
    document_types = frozenset(document_type_match.groups())

    category_section = _field_section(text, "category")
    categories = frozenset(
        re.findall(rf"^[-*]\s+{BACKTICK}([^\x60]+){BACKTICK}\s*$", category_section, re.MULTILINE)
    )
    if not categories:
        raise RecipeIndexError("Skillからcategoryの許可値を読み取れません")

    status_section = _field_section(text, "status")
    statuses = frozenset(
        re.findall(rf"^\|\s*{BACKTICK}([^\x60]+){BACKTICK}\s*\|", status_section, re.MULTILINE)
    )
    if not statuses:
        raise RecipeIndexError("Skillからstatusの許可値を読み取れません")

    source_section = _field_section(text, "source")
    source_tail = source_section.split(f"利用可能な {BACKTICK}type{BACKTICK}:", 1)[-1]
    source_types = frozenset(
        re.findall(rf"^[-*]\s+{BACKTICK}([^\x60]+){BACKTICK}\s*$", source_tail, re.MULTILINE)
    )
    array_fields = frozenset(
        key
        for key, value in {**required_example, **optional_example}.items()
        if isinstance(value, list)
    )
    date_fields = frozenset(
        field
        for field in (*required, *optional)
        if field != "title"
        and ("YYYY-MM-DD" in _field_section(text, field) or "日付" in _field_section(text, field))
    )

    return SkillSchema(
        required_fields=required,
        optional_fields=optional,
        document_types=document_types,
        categories=categories,
        statuses=statuses,
        source_types=source_types,
        array_fields=array_fields,
        date_fields=date_fields,
    )


def _target_paths(root: Path) -> list[Path]:
    recipes_root = root / "recipes"
    if not recipes_root.is_dir():
        raise RecipeIndexError("recipes/ が存在しません")
    return sorted(
        (
            path
            for path in recipes_root.rglob("*.md")
            if path.name not in EXCLUDED_NAMES
            and path.parent.name != "skills"
            and "docs" not in path.relative_to(root).parts
        ),
        key=lambda path: path.relative_to(root).as_posix(),
    )


def _split_front_matter(path: Path, include_body: bool) -> tuple[dict[str, Any], str | None]:
    lines = path.read_text(encoding="utf-8-sig").splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        raise RecipeIndexError(f"{path}: Front Matterがありません")
    closing_index = next(
        (index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---"),
        None,
    )
    if closing_index is None:
        raise RecipeIndexError(f"{path}: Front Matterの終了区切りがありません")
    try:
        metadata = yaml.safe_load("".join(lines[1:closing_index]))
    except yaml.YAMLError as exc:
        raise RecipeIndexError(f"{path}: YAML parse error: {exc}") from exc
    if not isinstance(metadata, dict):
        raise RecipeIndexError(f"{path}: Front MatterはYAML mappingで指定してください")
    body = "".join(lines[closing_index + 1 :]) if include_body else None
    return metadata, body


def _validate_date(value: Any, field: str, path: Path, errors: list[str]) -> None:
    value_text = str(value)
    try:
        parsed = date.fromisoformat(value_text)
    except (TypeError, ValueError):
        errors.append(f"{path}: {field}はYYYY-MM-DD形式で指定してください: {value!r}")
        return
    if parsed.isoformat() != value_text:
        errors.append(f"{path}: {field}はYYYY-MM-DD形式で指定してください: {value!r}")


def _validate_document(
    path: Path,
    metadata: dict[str, Any],
    body: str,
    root: Path,
    schema: SkillSchema,
) -> list[str]:
    errors: list[str] = []
    missing = [field for field in schema.required_fields if field not in metadata]
    if missing:
        errors.append(f"{path}: 必須フィールド不足: {', '.join(missing)}")
    unknown = sorted(set(metadata) - schema.allowed_fields)
    if unknown:
        errors.append(f"{path}: 未定義フィールド: {', '.join(unknown)}")

    expected_order = [field for field in (*schema.required_fields, *schema.optional_fields) if field in metadata]
    if list(metadata) != expected_order:
        errors.append(f"{path}: Front Matterのフィールド順がSkillの定義と一致しません")

    title = metadata.get("title")
    if not isinstance(title, str) or not title.strip():
        errors.append(f"{path}: titleは空でない文字列で指定してください")
    document_type = metadata.get("document_type")
    if document_type not in schema.document_types:
        errors.append(f"{path}: document_typeが許可値ではありません: {document_type!r}")
    category = metadata.get("category")
    if category not in schema.categories:
        errors.append(f"{path}: categoryが許可値ではありません: {category!r}")
    status = metadata.get("status")
    if status not in schema.statuses:
        errors.append(f"{path}: statusが許可値ではありません: {status!r}")
    if document_type == "standard" and status != "standard":
        errors.append(f"{path}: document_type: standardにはstatus: standardが必要です")
    if document_type == "history" and isinstance(title, str) and HISTORY_TITLE_DATE_PREFIX.match(title):
        errors.append(f"{path}: historyのtitleには調理日を含めず、created_atを使用してください")

    for field in schema.date_fields:
        if field in metadata:
            _validate_date(metadata[field], field, path, errors)

    tags = metadata.get("tags")
    if not isinstance(tags, list) or not tags or not all(isinstance(tag, str) and tag for tag in tags):
        errors.append(f"{path}: tagsは1件以上の文字列配列で指定してください")
    elif len(tags) != len(set(tags)):
        errors.append(f"{path}: tagsに重複があります")

    for field in schema.array_fields:
        if field in metadata and (
            not isinstance(metadata[field], list)
            or not all(isinstance(item, str) and item for item in metadata[field])
        ):
            errors.append(f"{path}: {field}は文字列配列で指定してください")

    servings = metadata.get("servings")
    if servings is not None and (isinstance(servings, bool) or not isinstance(servings, (int, float))):
        errors.append(f"{path}: servingsは数値で指定してください")
    rating = metadata.get("rating")
    if rating is not None and (
        isinstance(rating, bool) or not isinstance(rating, int) or not 1 <= rating <= 5
    ):
        errors.append(f"{path}: ratingは1から5の整数で指定してください")

    source = metadata.get("source")
    if source is not None:
        if not isinstance(source, dict) or not isinstance(source.get("type"), str):
            errors.append(f"{path}: sourceはtypeを持つmappingで指定してください")
        elif source.get("type") not in schema.source_types:
            errors.append(f"{path}: source.typeが許可値ではありません: {source.get('type')!r}")

    related = metadata.get("related")
    if related is not None:
        if not isinstance(related, dict) or not all(isinstance(value, str) for value in related.values()):
            errors.append(f"{path}: relatedは文字列値のmappingで指定してください")
        else:
            root_resolved = root.resolve()
            for related_path in related.values():
                candidate = (root / related_path).resolve()
                try:
                    candidate.relative_to(root_resolved)
                except ValueError:
                    errors.append(f"{path}: relatedがrepository外を参照しています: {related_path}")
                else:
                    if not candidate.is_file():
                        errors.append(f"{path}: relatedの参照先がありません: {related_path}")

    first_heading = next(
        (match.group(1).strip() for line in body.splitlines() if (match := re.match(r"^#\s+(.+?)\s*$", line))),
        None,
    )
    if first_heading != title:
        errors.append(f"{path}: titleと本文先頭のH1が一致しません")
    return errors


def load_schema(root: Path) -> SkillSchema:
    skill_path = root / SKILL_RELATIVE_PATH
    if not skill_path.is_file():
        raise RecipeIndexError(f"schema SSOTがありません: {skill_path}")
    return _parse_skill_schema(skill_path)


def validate_repository(root: Path) -> tuple[list[RecipeDocument], list[str]]:
    schema = load_schema(root)
    documents: list[RecipeDocument] = []
    errors: list[str] = []
    for path in _target_paths(root):
        try:
            metadata, body = _split_front_matter(path, include_body=True)
        except RecipeIndexError as exc:
            errors.append(str(exc))
            continue
        document_errors = _validate_document(path, metadata, body or "", root, schema)
        if document_errors:
            errors.extend(document_errors)
        else:
            documents.append(RecipeDocument(path=path, metadata=metadata, body=body))
    return documents, errors


def load_for_generation(root: Path) -> list[RecipeDocument]:
    documents: list[RecipeDocument] = []
    errors: list[str] = []
    for path in _target_paths(root):
        try:
            metadata, _ = _split_front_matter(path, include_body=False)
        except RecipeIndexError as exc:
            errors.append(str(exc))
            continue
        documents.append(RecipeDocument(path=path, metadata=metadata))
    if errors:
        raise RecipeIndexError("\n".join(errors))
    return documents


def _rating_display(value: Any) -> str:
    if value is None:
        return ""
    return f"{'★' * value}{'☆' * (5 - value)} ({value})"


def render_index(documents: list[RecipeDocument], root: Path) -> str:
    grouped: dict[str, list[RecipeDocument]] = {}
    for document in documents:
        grouped.setdefault(str(document.metadata["category"]), []).append(document)

    lines = [
        GENERATED_NOTICE,
        "",
        "## Recipe Index",
        "",
        "このファイルはレシピMarkdownのYAML Front Matterから自動生成しています。手編集せず、Front Matter変更後に再生成してください。",
        "",
    ]
    for category in sorted(grouped):
        lines.extend([f"### {category}", ""])
        category_documents = sorted(
            grouped[category],
            key=lambda document: (
                TYPE_ORDER.get(str(document.metadata["document_type"]), 99),
                -date.fromisoformat(str(document.metadata["created_at"])).toordinal(),
                document.path.relative_to(root).as_posix(),
            ),
        )
        for document_type in ("standard", "history", "reference"):
            typed_documents = [
                document for document in category_documents if document.metadata["document_type"] == document_type
            ]
            if not typed_documents:
                continue
            heading = {"standard": "標準レシピ", "history": "履歴・試作", "reference": "参考資料"}[document_type]
            lines.extend(
                [
                    f"#### {heading}",
                    "",
                    "| date | title | document_type | status | rating | servings | link |",
                    "| --- | --- | --- | --- | --- | --- | --- |",
                ]
            )
            for document in typed_documents:
                metadata = document.metadata
                title = str(metadata["title"]).replace("|", "\\|")
                lines.append(
                    f"| {metadata['created_at']} | {title} | {metadata['document_type']} | "
                    f"{metadata['status']} | {_rating_display(metadata.get('rating'))} | "
                    f"{metadata.get('servings', '')} | [open]({document.path.relative_to(root).as_posix()}) |"
                )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generated_index(root: Path) -> str:
    return render_index(load_for_generation(root), root)


def _read_text_preserving_newlines(path: Path) -> str:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return handle.read()


def _replace_recipe_index(readme: str, index: str) -> str:
    if readme.count(RECIPE_INDEX_START) != 1 or readme.count(RECIPE_INDEX_END) != 1:
        raise RecipeIndexError(
            f"{README_RELATIVE_PATH}にはrecipe-indexのstart/end markerを各1つ配置してください"
        )
    marker_pattern = re.compile(
        re.escape(RECIPE_INDEX_START) + r".*?" + re.escape(RECIPE_INDEX_END),
        re.DOTALL,
    )
    match = marker_pattern.search(readme)
    if match is None:
        raise RecipeIndexError(
            f"{README_RELATIVE_PATH}のrecipe-index markerの順序が正しくありません"
        )
    newline = "\r\n" if "\r\n" in readme else "\n"
    normalized_index = index.replace("\r\n", "\n").rstrip("\n").replace("\n", newline)
    replacement = newline.join(
        (RECIPE_INDEX_START, "", normalized_index, "", RECIPE_INDEX_END)
    )
    return readme[: match.start()] + replacement + readme[match.end() :]


def _update_readme(root: Path, index: str) -> tuple[Path, str]:
    output = root / README_RELATIVE_PATH
    if not output.is_file():
        raise RecipeIndexError(f"生成先がありません: {output}")
    current = _read_text_preserving_newlines(output)
    updated = _replace_recipe_index(current, index)
    if updated != current:
        with output.open("w", encoding="utf-8", newline="") as handle:
            handle.write(updated)
    return output, updated


def validate_command(root: Path) -> int:
    try:
        documents, errors = validate_repository(root)
    except RecipeIndexError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    if errors:
        print("\n".join(errors), file=sys.stderr)
        print(f"FAIL: {len(errors)}件の問題 / 有効な対象 {len(documents)}件", file=sys.stderr)
        return 1
    print(f"PASS: Front Matter {len(documents)}件")
    return 0


def generate_command(root: Path) -> int:
    try:
        content = generated_index(root)
        output, _ = _update_readme(root, content)
    except (RecipeIndexError, KeyError, ValueError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(f"生成しました: {output}")
    return 0


def check_command(root: Path) -> int:
    try:
        documents, errors = validate_repository(root)
        if errors:
            print("\n".join(errors), file=sys.stderr)
            print(f"FAIL: validation {len(errors)}件", file=sys.stderr)
            return 1
        output = root / README_RELATIVE_PATH
        actual = _read_text_preserving_newlines(output) if output.is_file() else ""
        expected = _replace_recipe_index(actual, render_index(documents, root))
    except (RecipeIndexError, OSError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    if actual != expected:
        print(f"FAIL: {output} がFront Matterから生成した結果と一致しません", file=sys.stderr)
        return 1
    print(f"PASS: validation {len(documents)}件 / index差分なし")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("validate", "generate", "check"))
    parser.add_argument("--root", type=Path, default=ROOT, help="repository root")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    if args.command == "validate":
        return validate_command(root)
    if args.command == "generate":
        return generate_command(root)
    return check_command(root)


if __name__ == "__main__":
    raise SystemExit(main())
